#!/bin/sh

pkill ssh-agent
eval $(ssh-agent -s)

# Necessary to make chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=cinnamon  # gnome for trusty.

# NOTE: This may break your compose key.
# See http://g/i3-users/YBexXGbik7E for more details.
export GTK_IM_MODULE=xim

# Desktop background color.
xsetroot -solid "#000000"

xset s off

. ~/.xinitrc
