#!/bin/bash

xrdb ~/.Xresources

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

dunst &

xrandr --output DP-4 --primary --mode 5120x1440 --output DP-2 --off

xset s off

exec i3
